# Generated by Django 4.2.3 on 2023-07-11 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsadashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfqmodel',
            name='complimentarySins',
        ),
    ]
