# Generated by Django 4.2.3 on 2023-07-19 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsadashboard', '0002_category_tokensgsa_delete_account_rfqmodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfqmodel',
            name='category',
        ),
    ]
