# Generated by Django 4.2.3 on 2023-07-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsadashboard', '0002_remove_rfqmodel_complimentarysins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='codeGSA',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='docName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='docPath',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='docSeqNum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='docSessionDate',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='docSessionId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='docType',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='seqNum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='modifications',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='modifications',
            name='time',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='modifications',
            name='versionNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rfqmodel',
            name='awardCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rfqmodel',
            name='cancelTime',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='rfqmodel',
            name='closeHour',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='rfqmodel',
            name='closeHourPMAM',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rfqmodel',
            name='closeTime',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='rfqmodel',
            name='closedDate',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='rfqmodel',
            name='daysOpen',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rfqmodel',
            name='deliveryDays',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rfqmodel',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='rfqmodel',
            name='idGSA',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='rfqmodel',
            name='idOld',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rfqmodel',
            name='issueTime',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='rfqmodel',
            name='leadTime',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='rfqmodel',
            name='password',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='rfqmodel',
            name='popEndDate',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='rfqmodel',
            name='popStartDate',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='rfqmodel',
            name='quoteCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rfqmodel',
            name='referenceNum',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rfqmodel',
            name='shipInd',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rfqmodel',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rfqmodel',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rfqmodel',
            name='valid',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='userowner',
            name='agency',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userowner',
            name='agencyCode',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userowner',
            name='idGSA',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userowner',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userowner',
            name='userEmail',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
