# Generated by Django 4.2.3 on 2023-07-14 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsadashboard', '0004_alter_account_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfqmodel',
            name='account',
        ),
    ]
