# Generated by Django 4.2.3 on 2023-07-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsadashboard', '0005_historysync'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
