# Generated by Django 4.2.3 on 2023-07-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsadashboard', '0006_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='activeSearch',
            field=models.BooleanField(default=False),
        ),
    ]
