# Generated by Django 4.2.3 on 2023-07-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsadashboard', '0008_keyword_rfqkeyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
