# Generated by Django 4.2.3 on 2023-08-15 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gsadashboard', '0009_keyword_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryByRFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryId', models.CharField(max_length=50)),
                ('schedule', models.CharField(max_length=50)),
                ('sin', models.CharField(max_length=35, null=True)),
                ('subCategory', models.IntegerField(null=True)),
                ('subCategoryDescription', models.TextField(null=True)),
                ('vendorCount', models.IntegerField(null=True)),
                ('alreadyExists', models.BooleanField(default=False)),
                ('valid', models.BooleanField(default=False)),
                ('hideInEbuy', models.BooleanField(default=False)),
                ('scheduleTitle', models.CharField(max_length=50, null=True)),
                ('sinDescription1', models.CharField(max_length=50, null=True)),
                ('sinDescription2', models.CharField(max_length=50, null=True)),
                ('scheduleTypeId', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractNum', models.CharField(max_length=50)),
                ('schedule', models.CharField(max_length=50)),
                ('sin', models.CharField(max_length=35, null=True)),
                ('subCategory', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=100)),
                ('vendorCategoryKey', models.CharField(max_length=100)),
                ('companyName', models.CharField(max_length=100)),
                ('otherCategories', models.CharField(max_length=100)),
                ('arravendor', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gsadashboard.categorybyrfq')),
            ],
        ),
        migrations.AlterField(
            model_name='rfqcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gsadashboard.categorybyrfq'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
