# Generated by Django 4.2.3 on 2023-08-15 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gsadashboard', '0010_categorybyrfq_vendorcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressType', models.CharField(max_length=50, null=True)),
                ('addressDepartment', models.CharField(max_length=50, null=True)),
                ('homeAddressAcknowledgement', models.BooleanField(default=False)),
                ('country', models.CharField(max_length=50, null=True)),
                ('countryName', models.CharField(max_length=50, null=True)),
                ('addressName', models.CharField(max_length=100, null=True)),
                ('agencyName', models.CharField(max_length=100, null=True)),
                ('addressLine1', models.CharField(max_length=100, null=True)),
                ('addressLine2', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('zipCode', models.CharField(max_length=50, null=True)),
                ('defaultAddress', models.BooleanField(default=False)),
                ('freightAddress', models.CharField(max_length=100, null=True)),
                ('crpAddress', models.CharField(max_length=100, null=True)),
                ('billingAddress', models.CharField(max_length=100, null=True)),
                ('invoiceAddress', models.CharField(max_length=100, null=True)),
                ('crpAAC', models.CharField(max_length=100, null=True)),
                ('dodAAC', models.CharField(max_length=100, null=True)),
                ('markFor', models.CharField(max_length=100, null=True)),
                ('irsDataName', models.CharField(max_length=50, null=True)),
                ('irsDataEmail', models.CharField(max_length=50, null=True)),
                ('irsDataPhone', models.CharField(max_length=50, null=True)),
                ('nameNotes', models.CharField(max_length=50, null=True)),
                ('emailNotes', models.CharField(max_length=100, null=True)),
                ('phoneNotes', models.CharField(max_length=100, null=True)),
                ('shippingAacId', models.CharField(max_length=100, null=True)),
                ('exportIndicator', models.CharField(max_length=100, null=True)),
                ('controlProgram', models.CharField(max_length=100, null=True)),
                ('valid', models.BooleanField(default=False)),
                ('addressEmpty', models.BooleanField(default=False)),
                ('irsDataExists', models.BooleanField(default=False)),
                ('mandatorySet', models.BooleanField(default=False)),
                ('invidualReceivingInfoValid', models.BooleanField(default=False)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gsadashboard.rfqmodel')),
            ],
        ),
    ]
