# Generated by Django 4.2.3 on 2023-08-17 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gsadashboard', '0011_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='historysync',
            name='keyword',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='LuchRFQComents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50, null=True)),
                ('comment', models.TextField(null=True)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gsadashboard.rfqmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
