# Generated by Django 4.2.3 on 2023-08-17 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gsadashboard', '0014_remove_rfqhistorysync_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorybyrfq',
            name='rfq',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='gsadashboard.rfqmodel'),
        ),
        migrations.DeleteModel(
            name='RFQCategory',
        ),
    ]
