# Generated by Django 4.2.3 on 2023-08-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsadashboard', '0016_alter_categorybyrfq_alreadyexists_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorcategory',
            name='companyName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
