# Generated by Django 4.2.3 on 2023-08-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsadashboard', '0017_alter_vendorcategory_companyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqmodel',
            name='syncLuch',
            field=models.BooleanField(default=False),
        ),
    ]
